import Head from 'next/head';
import Layout from '@/components/Layout';
import Image from 'next/image';
import profilePic from '../../public/images/profile/jeyna-profile.png';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import HireMe from '@/components/HireMe';
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-full'>
            <div className='w-1/2'>
              <Image src={profilePic} alt='jeyna' className='w-full h-auto' />
            </div>
            <div className='w-1/2 flex flex-col items-center'>
              <AnimatedText
                // text='Turning Vision Into Reality With Code And Design'
                text='Hello!'
                className='text-2xl'
              />
              <div className='flex flex-col justify-start '>
                <p className='text-5xl font-bold mt-10'>👋🏻 I'm Jeyna Kim</p>
                <p className='mt-3'>
                  ___________ A Passionate Full-Stack Web Developer hailing from
                  Toronto, ON
                </p>
                <p className='my-4 text-base font-medium'>
                  Passionate about turning ideas into digital reality, I
                  specialize in creating innovative web applications. Explore my
                  projects and discover how I blend creativity, functionality,
                  and user-centered design!
                </p>

                <div className='flex items-center self-start mt-4'>
                  <Link
                    href='https://resume.creddle.io/resume/b5p8hv43jyy'
                    target={'_blank'}
                    className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light'
                    // download={true}
                  >
                    Resume <LinkArrow className={'w-6 ml-1'} />
                  </Link>
                  <Link
                    href='mailto:jeyna.kimm@gmail.com'
                    target={'_blank'}
                    className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light'
                  >
                    Contact
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className='absolute right-8 bottom-8 inline-blcok w-24'>
          <Image src={lightBulb} alt='Jeyna' className='w-full h-auto' />
        </div>
      </main>
    </>
  );
}
